In [1]:
from SteerEnergyStorage.Formulations.ElectrodeFormulations import CathodeFormulation, AnodeFormulation
from SteerEnergyStorage.Constructions.Electrodes import Cathode, Anode
# from SteerEnergyStorage.Formulations.ElectrodeAssemblies import CylindricalJellyRoll
# from SteerEnergyStorage.Constructions.Cells import CylindricalCell
# from SteerEnergyStorage.Constructions.Containers import CylindricalCanister, CylindricalLidAssembly, CylindricalTerminalConnector, CylindricalCase
from SteerEnergyStorage.Materials.ElectrodeMaterials import CathodeMaterial, AnodeMaterial, Binder, ConductiveAdditive
from SteerEnergyStorage.Materials.CurrentCollectors import TablessCurrentCollector
from SteerEnergyStorage.Materials.Separators import Separator
from SteerEnergyStorage.Materials.Electrolytes import Electrolyte
from SteerEnergyStorage.Materials.RawMaterials import CurrentCollectorMaterial, InsulationMaterial


import pandas as pd

In [2]:
cathode_current_collector_material = CurrentCollectorMaterial.from_database(name='Aluminum')

cathode_current_collector = TablessCurrentCollector(
    material = cathode_current_collector_material,
    length = 2600,
    width = 120,
    coated_width = 110,
    thickness = 15,
    bare_lengths_a_side = (20, 200),
    bare_lengths_b_side = (10, 200),
    insulation_width = 3
)

In [3]:
properties = cathode_current_collector.properties

pd.DataFrame(
    list(properties.items()), 
    columns=['Property', 'Value']
)

                  Property       Value
0                     Mass     12.64 g
1                     Cost      0.03 $
2  Total single sided area  3120.0 cm²
3        Total coated area  5103.9 cm²
4    Total insulation area   143.1 cm²

In [4]:
cathode_current_collector.get_a_side_view(width=900, height=600)

In [5]:
cathode_current_collector.get_b_side_view(width=900, height=600)

In [6]:
anode_current_collector_material = CurrentCollectorMaterial.from_database(name='Copper')

anode_current_collector = TablessCurrentCollector(
    material = anode_current_collector_material,
    length = 2650,
    width = 128,
    coated_width = 116,
    thickness = 10,
    bare_lengths_a_side = (20, 200),
    bare_lengths_b_side = (10, 200),
    insulation_width = 3
)

In [7]:
properties = anode_current_collector.properties

pd.DataFrame(
    list(properties.items()), 
    columns=['Property', 'Value']
)

                  Property       Value
0                     Mass     32.77 g
1                     Cost       0.2 $
2  Total single sided area  3392.0 cm²
3        Total coated area  5503.1 cm²
4    Total insulation area   146.1 cm²

In [8]:
anode_current_collector.get_a_side_view(width=900, height=600)

In [9]:
anode_current_collector.get_b_side_view(width=900, height=600)

In [10]:
cathode_active_material1 = CathodeMaterial.from_database(name='LFP')
cathode_active_material2 = CathodeMaterial.from_database(name='NMC811')
cathode_binder = Binder.from_database(name='PVDF')
cathode_conductive_additive = ConductiveAdditive.from_database(name='Super P')

In [11]:
anode_active_material = AnodeMaterial.from_database(name='Hard Carbon (Vendor A)')
anode_binder = Binder.from_database(name='SBR')
anode_conductive_additive = ConductiveAdditive.from_database(name='Graphite')

In [12]:

cathode_formulation = CathodeFormulation(
    active_materials={
        cathode_active_material1: 49, 
        cathode_active_material2: 49
    },
    binders={
        cathode_binder: 1
    },
    conductive_additives={
        cathode_conductive_additive: 1
    }
)

cathode_formulation.voltage_cuttoff = 4.1

(cathode_formulation
 .plot_half_cell_curve(
     add_materials=False, 
     width=800, 
     height=450
 ).show()
)

In [13]:
anode_formulation = AnodeFormulation(
    active_materials={anode_active_material: 96},
    binders={anode_binder: 2},
    conductive_additives={anode_conductive_additive: 2}
)

anode_formulation.plot_half_cell_curve(add_materials=True, width=600, height=350).show()

In [14]:
insulation_material = InsulationMaterial.from_database(name='Aluminium Oxide, 95%')

cathode = Cathode(
    formulation=cathode_formulation,
    current_collector=cathode_current_collector,
    calender_density=2.6,
    mass_loading=10.6,
    insulation_material=insulation_material,
    insulation_thickness=15
)

In [15]:
mass_breakdown = cathode.mass_breakdown

pd.DataFrame(
    list(mass_breakdown.items()), 
    columns=['Property', 'Value (g)']
)

                    Property  Value (g)
0                        LFP      22.98
1                     NMC811      30.63
2                       PVDF       0.23
3                    Super P       0.26
4  Tabless Current Collector      12.64
5       Aluminium Oxide, 95%       0.78

In [16]:
cost_breakdown = cathode.cost_breakdown

pd.DataFrame(
    list(cost_breakdown.items()), 
    columns=['Property', 'Value ($)']
)

                    Property  Value ($)
0                        LFP       0.16
1                     NMC811       0.66
2                       PVDF       0.05
3                    Super P       0.01
4  Tabless Current Collector       0.03
5       Aluminium Oxide, 95%       0.00

In [17]:
properties = cathode.properties

pd.DataFrame(
    list(properties.items()), 
    columns=['Property', 'Value']
)

            Property     Value
0               Mass   67.52 g
1       Coating mass    54.1 g
2    Total thickness  96.54 um
3  Coating thickness  40.77 um
4           Porosity   35.31 %
5               Cost    $ 0.93

In [18]:
cathode.get_a_side_view(width=900, height=600)

In [19]:
cathode.get_b_side_view(width=900, height=600)

In [20]:
cathode.get_end_view(width=1300, height=300).show()

In [21]:
cathode.voltage_cuttoff = 4
cathode.plot_half_cell_curve(width=600, height=400).show()
cathode.plot_half_cell_curve(areal=True, width=600, height=400).show()

In [22]:

anode = Anode(
    formulation=anode_formulation,
    current_collector=anode_current_collector,
    calender_density=1.1,
    mass_loading=7.5,
    insulation_material=insulation_material,
    insulation_thickness=15
)

In [23]:
mass_breakdown = anode.mass_breakdown

pd.DataFrame(
    list(mass_breakdown.items()), 
    columns=['Property', 'Value (g)']
)

                    Property  Value (g)
0     Hard Carbon (Vendor A)      39.55
1                        SBR       0.52
2                   Graphite       1.21
3  Tabless Current Collector      32.77
4       Aluminium Oxide, 95%       0.80

In [24]:
cost_breakdown = anode.cost_breakdown

pd.DataFrame(
    list(cost_breakdown.items()), 
    columns=['Property', 'Value ($)']
)

                    Property  Value ($)
0     Hard Carbon (Vendor A)       0.28
1                        SBR       0.01
2                   Graphite       0.01
3  Tabless Current Collector       0.20
4       Aluminium Oxide, 95%       0.00

In [25]:
properties = anode.properties

pd.DataFrame(
    list(properties.items()), 
    columns=['Property', 'Value']
)

            Property      Value
0               Mass    74.84 g
1       Coating mass    41.27 g
2    Total thickness  146.36 um
3  Coating thickness   68.18 um
4           Porosity    26.26 %
5               Cost      $ 0.5

In [26]:
anode.get_a_side_view(width=900, height=600).show()

In [27]:
anode.get_b_side_view(width=900, height=600).show()

In [28]:
anode.get_end_view(width=1300, height=300).show()

In [29]:
anode.plot_half_cell_curve(width=600, height=400).show()
anode.plot_half_cell_curve(areal=True, width=600, height=400).show()

In [30]:
# construct seperator
separator = Separator(thickness=16, 
                      areal_cost=0.9, 
                      density=0.4, 
                      width=75, 
                      porosity=47, 
                      fold_length=current_collector_length+100)


figure = separator.get_top_down_view(width=580)
figure.show()

NameError: name 'current_collector_length' is not defined

In [ ]:
cylindrical_jelly_roll = CylindricalJellyRoll(anode=anode, 
                                              cathode=cathode,
                                              separator=separator, 
                                              internal_die_diameter=3)

In [ ]:
figure = cylindrical_jelly_roll.get_layup()
figure.show()

In [ ]:
cylindrical_jelly_roll.get_top_down_view(width=1100, height=800).show()

In [ ]:
cylindrical_jelly_roll.get_side_view(width=1100, height=800).show()

In [ ]:
# build the electrolyte
electrolyte = Electrolyte(specific_cost=8.94, density=1.2)

In [ ]:
# build the encapsulation
cylindrical_shell = CylindricalCanister(formula='Al',
                                        outer_diameter=21,
                                        wall_thickness=0.4,
                                        length=115)

lid_assembly = CylindricalLidAssembly(cost=0.2, mass=2, thickness=6)

cathode_terminal_collector = CylindricalTerminalCollector(formula='Al', diameter=14, thickness=1, fill_factor=0.7)
anode_terminal_collector = CylindricalTerminalCollector(formula='Al', diameter=14, thickness=1, fill_factor=0.7)

case = CylindricalCase(canister=cylindrical_shell, 
                       lid_assembly=lid_assembly,
                       cathode_terminal_collector=cathode_terminal_collector,
                       anode_terminal_collector=anode_terminal_collector)

case.get_top_down_view().show()
case.get_bottom_up_view().show()
case.get_side_view(width=500, height=600).show()

In [ ]:
cylindrical_jelly_roll.get_top_down_view(encapsulation=case ,width=1100, height=800).show()

In [ ]:
cylindrical_jelly_roll.get_side_view(encapsulation=case, width=1100, height=800).show()

In [ ]:
# build the cell
cell = CylindricalCell(electrode_assembly=cylindrical_jelly_roll,
                        electrolyte=electrolyte,
                        electrolyte_overfill=10,
                        encapsulation=case,
                        reversible_capacity=5,
                        irreversible_capacity=0.2)

In [ ]:
figure = cell.get_capacity_voltage_plot(width=900, height=600)
figure.show()

In [ ]:

print(f"The energy the cell can hold is {cell.energy} Wh")
print(f"The specific energy of the cell is {cell.specific_energy} Wh/kg")
print(f"The cost of the cell is {cell.cost} $")
print(f"The normalized cost of the cell is {cell.normalized_cost} $/kWh")
print(f"The energy density of the cell is {cell.energy_density} Wh/L")

In [ ]:
cell.cost_breakdown

In [ ]:
figure = cell.get_cost_breakdown_plot(width=600, height=600)
figure.show()

In [ ]:
figure = cell.get_mass_breakdown_plot(width=600, height=600)
figure.show()