In [1]:
from SteerEnergyStorage.Formulations.ElectrodeFormulations import CathodeFormulation, AnodeFormulation
# from SteerEnergyStorage.Constructions.Electrodes import Cathode, Anode
# from SteerEnergyStorage.Formulations.ElectrodeAssemblies import CylindricalJellyRoll
# from SteerEnergyStorage.Constructions.Cells import CylindricalCell
# from SteerEnergyStorage.Constructions.Containers import CylindricalCanister, CylindricalLidAssembly, CylindricalTerminalConnector, CylindricalCase
from SteerEnergyStorage.Materials.ElectrodeMaterials import CathodeMaterial, AnodeMaterial, Binder, ConductiveAdditive
from SteerEnergyStorage.Materials.CurrentCollectors import TablessCurrentCollector
from SteerEnergyStorage.Materials.Separators import Separator
from SteerEnergyStorage.Materials.Electrolytes import Electrolyte
from SteerEnergyStorage.Materials.RawMaterials import CurrentCollectorMaterial

import pandas as pd

In [2]:
cathode_current_collector_material = CurrentCollectorMaterial.from_database(name='Aluminum')

cathode_current_collector = TablessCurrentCollector(
    material = cathode_current_collector_material,
    length = 2600,
    width = 120,
    coated_width = 110,
    thickness = 12,
    bare_lengths_a_side = (20, 200),
    bare_lengths_b_side = (10, 200),
    insulation_width = 3
)

In [3]:
properties = cathode_current_collector.properties

pd.DataFrame(
    list(properties.items()), 
    columns=['Property', 'Value']
)

                  Property       Value
0                     Mass     10.11 g
1                     Cost      0.02 $
2  Total single sided area  3120.0 cm²
3        Total coated area  5103.9 cm²
4    Total insulation area   143.1 cm²

In [4]:
cathode_current_collector.get_a_side_view(width=900, height=600)

In [5]:
cathode_current_collector.get_b_side_view(width=900, height=600)

In [6]:
anode_current_collector_material = CurrentCollectorMaterial.from_database(name='Copper')

anode_current_collector = TablessCurrentCollector(
    material = anode_current_collector_material,
    length = 2650,
    width = 128,
    coated_width = 116,
    thickness = 5,
    bare_lengths_a_side = (20, 200),
    bare_lengths_b_side = (10, 200),
    insulation_width = 3
)

In [7]:
properties = anode_current_collector.properties

pd.DataFrame(
    list(properties.items()), 
    columns=['Property', 'Value']
)

                  Property       Value
0                     Mass     16.38 g
1                     Cost       0.1 $
2  Total single sided area  3392.0 cm²
3        Total coated area  5503.1 cm²
4    Total insulation area   146.1 cm²

In [8]:
anode_current_collector.get_a_side_view(width=900, height=600)

In [9]:
anode_current_collector.get_b_side_view(width=900, height=600)

In [10]:
cathode_active_material = CathodeMaterial.from_database(name='NaNiMn P2-O3 Composite')

cathode_active_material.voltage_cuttoff = 4.2
cathode_active_material.reversible_capacity_scaling = 1
cathode_active_material.irreversible_capacity_scaling = 1

cathode_active_material.plot_half_cell_curve(width=600, height=350).show()

In [11]:
cathode_binder = Binder.from_database(name='PVDF')
cathode_conductive_additive = ConductiveAdditive.from_database(name='Super P')

In [12]:
anode_active_material = AnodeMaterial.from_database(name='Hard Carbon (Vendor A)')

anode_active_material.reversible_capacity_scaling = 1.05
anode_active_material.irreversible_capacity_scaling = 1

anode_active_material.plot_half_cell_curve(width=600, height=350).show()

In [13]:
anode_binder = Binder.from_database(name='SBR')
anode_conductive_additive = ConductiveAdditive.from_database(name='Graphite')

In [14]:
cathode_formulation = CathodeFormulation(
    active_materials={cathode_active_material: 89},
    binders={cathode_binder: 5},
    conductive_additives={cathode_conductive_additive: 6}
)

cathode_formulation.voltage_cuttoff = 4.2
cathode_formulation.plot_half_cell_curve(add_materials=True, width=600, height=350).show()

In [15]:
anode_formulation = AnodeFormulation(
    active_materials={anode_active_material: 88},
    binders={anode_binder: 3},
    conductive_additives={anode_conductive_additive: 9}
)

anode_formulation.plot_half_cell_curve(add_materials=True, width=600, height=350).show()

In [16]:


cathode = Cathode(formulation=cathode_formulation,
                    mass_loading=10.68,
                    current_collector=cathode_current_collector,
                    calender_density=2.60)

cathode_current_collector.get_top_down_view(width=400).show()

NameError: name 'Cathode' is not defined

In [ ]:

anode_formulation = ElectrodeFormulation(active_materials={anode_active_material: 88},
                                         binders={anode_binder: 3},
                                         conductive_additives={anode_conductive_additive: 9})

anode = Anode(formulation=anode_formulation,
              mass_loading=4.5,
              current_collector=anode_current_collector,
              calender_density=0.85)

figure = anode_current_collector.get_top_down_view(width=580)
#figure.update_layout(xaxis=dict(range=[1000, 1200]))
figure.show()

In [ ]:
# construct seperator
separator = Separator(thickness=16, 
                      areal_cost=0.9, 
                      density=0.4, 
                      width=75, 
                      porosity=47, 
                      fold_length=current_collector_length+100)


figure = separator.get_top_down_view(width=580)
figure.show()

In [ ]:
cylindrical_jelly_roll = CylindricalJellyRoll(anode=anode, 
                                              cathode=cathode,
                                              separator=separator, 
                                              internal_die_diameter=3)

In [ ]:
figure = cylindrical_jelly_roll.get_layup()
figure.show()

In [ ]:
cylindrical_jelly_roll.get_top_down_view(width=1100, height=800).show()

In [ ]:
cylindrical_jelly_roll.get_side_view(width=1100, height=800).show()

In [ ]:
# build the electrolyte
electrolyte = Electrolyte(specific_cost=8.94, density=1.2)

In [ ]:
# build the encapsulation
cylindrical_shell = CylindricalCanister(formula='Al',
                                        outer_diameter=21,
                                        wall_thickness=0.4,
                                        length=115)

lid_assembly = CylindricalLidAssembly(cost=0.2, mass=2, thickness=6)

cathode_terminal_collector = CylindricalTerminalCollector(formula='Al', diameter=14, thickness=1, fill_factor=0.7)
anode_terminal_collector = CylindricalTerminalCollector(formula='Al', diameter=14, thickness=1, fill_factor=0.7)

case = CylindricalCase(canister=cylindrical_shell, 
                       lid_assembly=lid_assembly,
                       cathode_terminal_collector=cathode_terminal_collector,
                       anode_terminal_collector=anode_terminal_collector)

case.get_top_down_view().show()
case.get_bottom_up_view().show()
case.get_side_view(width=500, height=600).show()

In [ ]:
cylindrical_jelly_roll.get_top_down_view(encapsulation=case ,width=1100, height=800).show()

In [ ]:
cylindrical_jelly_roll.get_side_view(encapsulation=case, width=1100, height=800).show()

In [ ]:
# build the cell
cell = CylindricalCell(electrode_assembly=cylindrical_jelly_roll,
                        electrolyte=electrolyte,
                        electrolyte_overfill=10,
                        encapsulation=case,
                        reversible_capacity=5,
                        irreversible_capacity=0.2)

In [ ]:
figure = cell.get_capacity_voltage_plot(width=900, height=600)
figure.show()

In [ ]:

print(f"The energy the cell can hold is {cell.energy} Wh")
print(f"The specific energy of the cell is {cell.specific_energy} Wh/kg")
print(f"The cost of the cell is {cell.cost} $")
print(f"The normalized cost of the cell is {cell.normalized_cost} $/kWh")
print(f"The energy density of the cell is {cell.energy_density} Wh/L")

In [ ]:
cell.cost_breakdown

In [ ]:
figure = cell.get_cost_breakdown_plot(width=600, height=600)
figure.show()

In [ ]:
figure = cell.get_mass_breakdown_plot(width=600, height=600)
figure.show()